FROM ubuntu:latest
WORKDIR /root
COPY --from=build /root/.idris2 /root/.idris2
# This ensures the extension works without additional configuration:
RUN ln -s /root/.idris2/bin/idris2 /bin/idris

ENV PATH="/root/.idris2/bin:${PATH}"
ENV LD_LIBRARY_PATH="/root/.idris2/lib:${LD_LIBRARY_PATH}"

RUN apt-get update && \
    apt-get install -y racket
