name: "Build Base Image"
description: "Builds the correct base image depending on the idris version"

inputs:
  idris-lsp-version:
    description: "The Idris version to build"
    required: false
    default: "latest"
  idris-version:
    description: "The Idris version to build"
    required: false
    default: "latest"
  base-tag:
    description: "Tag of the base image to use. Should be from base.Dockerfile"
    required: true
  push:
    description: "Whether to push the image to Docker Hub"
    required: false
    default: false
  load:
    description: "Whether to load the image into the local Docker daemon"
    required: false
    default: false
  tags:
    description: "The tag to use for the image"
    required: false
    default: idris-devcontainer-img
  labels:
    description: "The labels to apply to the image"
    required: false
    default: ""
  platforms: 
    description: "The platforms to build for"
    required: false
    default: "linux/amd64"

runs:
  using: composite
  steps:
    - name: Get Latest Idris Commit SHA
      id: get-sha
      uses: ./.github/actions/get-idris-sha
    
    # if platforms is not equal to linux/amd64, do not cache-to (output empty string)
    # See: https://github.com/joshuanianji/idris-2-docker/pull/71
    - name: Calculate cache-to
      id: calculate-cache-to
      run: |
        if [ "${{ inputs.platforms }}" == "linux/amd64" ]; then
          echo "cache-to=type=gha,mode=max,scope=build-devcontainer-${{ inputs.idris-version }}" >> $GITHUB_OUTPUT
        else
          echo "cache-to=" >> $GITHUB_OUTPUT
        fi
    
    - name: Build Devcontainer (versioned)
      if: ${{ inputs.idris-lsp-version != 'latest' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: devcontainer.Dockerfile
        platforms: ${{ inputs.platforms }}
        build-args: | 
          IDRIS_LSP_VERSION=${{ inputs.idris-lsp-version }}
          IDRIS_VERSION=${{ inputs.idris-version }}
          BASE_IMG=${{ inputs.base-tag }}
        tags: ${{ inputs.tags }}
        load: ${{ inputs.load }}
        push: ${{ inputs.push }}
        labels: ${{ inputs.labels }}
        cache-from: |
          type=gha,scope=build-devcontainer-${{ inputs.idris-version }}
          type=registry,ref=ghcr.io/joshuanianji/idris-2-docker/devcontainer:${{ inputs.idris-version }}
        cache-to: ${{ steps.calculate-cache-to.outputs.cache-to }}

    - name: Build Devcontainer (latest)
      if: ${{ inputs.idris-lsp-version == 'latest' }}
      uses: docker/build-push-action@v5
      with:
        context: .
        file: devcontainer-sha.Dockerfile
        platforms: ${{ inputs.platforms }}
        build-args: | 
          IDRIS_LSP_VERSION=${{ inputs.idris-lsp-version }}
          IDRIS_LSP_SHA=${{ steps.get-sha.outputs.lsp-sha }}
          IDRIS_VERSION=${{ inputs.idris-version }}
          IDRIS_SHA=${{ steps.get-sha.outputs.idris-sha }}
          BASE_IMG=${{ inputs.base-tag }}
        tags: ${{ inputs.tags }}
        load: ${{ inputs.load }}
        push: ${{ inputs.push }}
        labels: ${{ inputs.labels }}
        cache-from: |
          type=gha,scope=build-devcontainer-${{ inputs.idris-version }}
          type=registry,ref=ghcr.io/joshuanianji/idris-2-docker/devcontainer:${{ inputs.idris-version }}
        cache-to: ${{ steps.calculate-cache-to.outputs.cache-to }}
