name: Build and Deploy a Single Docker Image

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image-name:
        required: true
        type: string
      scope:
        description: "The scope of the image if doing Matrix builds"
        required: false
        type: string
        default: "public"
      test:
        description: "Whether to test the image"
        required: false
        type: boolean
        default: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      TAG: ghcr.io/${{ inputs.image-name }}:${{ inputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@be010b42938448d8a286c21d5c4ccf2aae1524a1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: create-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ inputs.image-name }}

      - name: Build test image
        if: ${{ inputs.test }}
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          load: true
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
          tags: ${{ env.TAG }}
          # Removed cache section because internal cache should be fine for this step

      - name: Run Test 1
        if: ${{ inputs.test }}
        run: |
          docker run --rm -it ${{ env.TAG }} idris2 --version

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
          tags: ${{ env.TAG }}
          labels: ${{ steps.create-meta.outputs.labels }}
          # When doing matrix builds, we need to scope the image
          # https://github.com/moby/buildkit/issues/2885
          cache-from: type=gha,scope=build-${{ inputs.scope }}
          cache-to: type=gha,mode=max,scope=build-${{ inputs.scope }}
