name: Base - Build/Test/Deploy 
# Reusable workflow to build, test and deploy the base image
# The reason I split the base and consumer CI files is that the logic for conditionally skipping tests would be too difficult to manage
# violating kiss just once never hurt...

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      image-name:
        required: true
        type: string
      scope:
        description: "The scope of the image if doing Matrix builds"
        required: false
        type: string
        default: "public"
      push: 
        description: "Whether to push the image to the registry"
        required: true
        type: boolean

env:
  TAG: ghcr.io/${{ inputs.image-name }}:${{ inputs.version }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha

      - name: Build Image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          file: base.Dockerfile
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
            IDRIS_SHA=${{ steps.get-sha.outputs.sha }}
          cache-from: type=gha,scope=build-test-${{ inputs.scope }}
          cache-to: type=gha,mode=max,scope=build-test-${{ inputs.scope }}

  test-1:
    name: Test 1
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha

      - name: Build Image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          load: true
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
            IDRIS_SHA=${{ steps.get-sha.outputs.sha }}
          tags: ${{ env.TAG }}-test
          # don't use cache-to, because we don't need to cache the image
          cache-from: type=gha,scope=build-test-${{ inputs.scope }}

      - name: Run Test 1
        run: |
          docker run ${{ env.TAG }}-test idris2 --version
  
  test-2:
    name: Test 2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha

      - name: Build Image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          load: true
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
            IDRIS_SHA=${{ steps.get-sha.outputs.sha }}
          tags: ${{ env.TAG }}-test
          cache-from: type=gha,scope=build-test-${{ inputs.scope }}

      - name: Run Test 2
        run: |
          docker run ${{ env.TAG }}-test /bin/bash -c "make clean; make all && make install"
  
  test-3:
    name: Test 3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha
      
      # Looks like a node backend helps for tests
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          load: true
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
            IDRIS_SHA=${{ steps.get-sha.outputs.sha }}
          tags: ${{ env.TAG }}-test
          cache-from: type=gha,scope=build-test-${{ inputs.scope }}

      - name: Run Test 3
        run: |
          docker run ${{ env.TAG }}-test /bin/bash -c "make clean; make all; make test"

  deploy:
    name: Deploy
    if: ${{ inputs.push }}
    needs: [test-1, test-2, test-3]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Buildx
        uses: "./.github/actions/setup-buildx"
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_ip: ${{ secrets.SSH_IP }}
      
      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha

      - name: Login to GHCR
        uses: docker/login-action@be010b42938448d8a286c21d5c4ccf2aae1524a1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: create-meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ inputs.image-name }}

      - name: Build and push
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: true
          file: ${{ inputs.dockerfile }}
          build-args: |
            IDRIS_VERSION=${{ inputs.version }}
            IDRIS_SHA=${{ steps.get-sha.outputs.sha }}
          tags: ${{ env.TAG }}
          labels: ${{ steps.create-meta.outputs.labels }}
          # When doing matrix builds, we need to scope the image
          # https://github.com/moby/buildkit/issues/2885
          cache-from: type=gha,scope=build-${{ inputs.scope }}
