name: Build Test and Deploy

on:
  push:
    branches:
      - main
    paths:
      - ".github/**/*.yml"
      - "*.Dockerfile"
      - "tests/*.sh"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**/*.yml"
      - "*.Dockerfile"
      - "tests/*.sh"

jobs:
  # base-build-test:
  #   name: Base Build and Test - ${{ matrix.idris-version }}
  #   strategy:
  #     matrix:
  #       idris-version: ["v0.5.1", "v0.6.0", "latest"]
  #   uses: ./.github/workflows/version-base-build-test.yml
  #   with:
  #     idris-version: ${{ matrix.idris-version }}
  #   secrets: inherit
  
  # base-deploy:
  #   name: Base Deploy - ${{ matrix.idris-version }}
  #   # only deploy if it's a push to main
  #   if: github.event_name == 'schedule' || github.event_name == 'push'
  #   needs: [base-build-test]
  #   strategy:
  #     matrix:
  #       idris-version: ["v0.5.1", "v0.6.0", "latest"]
  #     # deploy one at a time, so the latest is always the latest deployed
  #     max-parallel: 1 
  #   uses: ./.github/workflows/version-base-deploy.yml
  #   with:
  #     idris-version: ${{ matrix.idris-version }}
  #   secrets: inherit
  
  devcontainer-build-test:
    name: Devcontainer Build and Test - ${{ matrix.idris-lsp-version }}
    strategy:
      matrix:
        # based off of the branches in the idris-lsp repo
        idris-lsp-version: ["idris2-0.6.0", "latest"]
    uses: ./.github/workflows/version-devcontainer-build-test.yml
    with:
      idris-lsp-version: ${{ matrix.idris-lsp-version }}
    secrets: inherit
  
  devcontainer-deploy:
    name: Devcontainer Deploy - ${{ matrix.idris-lsp-version }}
    # only deploy if it's a push to main
    if: github.event_name == 'schedule' || github.event_name == 'push'
    needs: [devcontainer-build-test]
    strategy:
      matrix:
        idris-lsp-version: ["idris2-0.6.0", "latest"]
      max-parallel: 1 
    uses: ./.github/workflows/version-devcontainer-deploy.yml
    with:
      idris-lsp-version: ${{ matrix.idris-lsp-version }}
    secrets: inherit