name: TEST TESTS ETSET SETE T

on: 
  push:

jobs:
  consumer-build-test-1:
    name: Build Consumer - ${{ matrix.dockerfile }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idris-version: ["v0.6.0"]
        dockerfile: [debian]
    # use a local registry
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      # attempt to use bogus registry name so docker won't think this is a remote image
      # when using it as a base image in the Dockerfile
      # https://stackoverflow.com/a/70733299
      BASE_TAG: localhost:5000/base-${{ matrix.idris-version }}:latest
      TAG: idris-consumer-${{ matrix.dockerfile }}-${{ matrix.idris-version }}:test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Buildx (no ARM)
        uses: docker/setup-buildx-action@v2
        with:
          # since we're using a local registry
          driver-opts: network=host

      - name: Build Base
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: base.Dockerfile
          build-args: | 
            IDRIS_VERSION=${{ matrix.idris-version }}
          tags: ${{ env.BASE_TAG }}
          push: true
  
          # When doing matrix builds, we need to scope the image
          # https://github.com/moby/buildkit/issues/2885
          cache-from: type=gha,scope=build-base-${{ matrix.idris-version }}
          cache-to: type=gha,mode=max,scope=build-base-${{ matrix.idris-version }}
  

      - name: Run `docker image ls`
        run: docker image ls

      - name: Build ${{ matrix.dockerfile}}
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ${{ matrix.dockerfile }}.Dockerfile
          build-args: | 
            IDRIS_VERSION=${{ matrix.idris-version }}
            BASE_IMG=${{ env.BASE_TAG }}
          tags: ${{ env.TAG }}
          load: true

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: '1.8.2'

      - name: Setup Bats libs
        uses: brokenpip3/setup-bats-libs@0.1.0
        with:
          support-version: 0.3.0
          assert-version: 2.1.0
          file-install: false
          detik-install: false

      # LIB_PATH is a env var I use in the setup() function of my bats tests
      # it points to the folder containing bats-assert and bats-support
      - name: Run Test
        run: |
          export LIB_PATH=/usr/lib/
          export DOCKER_IMAGE=${{ env.TAG }}
          bats tests/consumer-idris.bats
