name: TEST TESTS ETSET SETE T

on: 
  push:

jobs:
  consumer-build-test-1:
    name: Build Consumer - ${{ matrix.dockerfile }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        idris-version: ["v0.6.0"]
        dockerfile: [debian]
    # use a local registry
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      # attempt to use bogus registry name so docker won't think this is a remote image
      # when using it as a base image in the Dockerfile
      # https://stackoverflow.com/a/70733299
      BASE_TAG: localhost:5000/base-${{ matrix.idris-version }}:latest
      TAG: idris-consumer-${{ matrix.dockerfile }}-${{ matrix.idris-version }}:test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Build Base
        id: build-base
        uses: ./.github/actions/build-image
        with:
          version: ${{ matrix.idris-version }}
          dockerfile: base
          tag: ${{ env.BASE_TAG }}
      
      - name: Run `docker image ls`
        run: docker image ls

      - name: Build
        uses: ./.github/actions/build-image
        with:
          version: ${{ matrix.idris-version }}
          dockerfile: ${{ matrix.dockerfile }}
          tag: ${{ env.TAG }}
          # referencing the tag I manually set keeps erroring, it tried to pull from docker.io!
          # https://stackoverflow.com/q/20481225
          # Instead, I'm referring to the image ID, maybe it'll work
          # https://stackoverflow.com/a/71565133
          build-args: |
            BASE_IMG=${{ env.BASE_TAG }}

      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: '1.8.2'

      - name: Setup Bats libs
        uses: brokenpip3/setup-bats-libs@0.1.0
        with:
          support-version: 0.3.0
          assert-version: 2.1.0
          file-install: false
          detik-install: false

      # LIB_PATH is a env var I use in the setup() function of my bats tests
      # it points to the folder containing bats-assert and bats-support
      - name: Run Test
        run: |
          export LIB_PATH=/usr/lib/
          export DOCKER_IMAGE=${{ env.TAG }}
          bats tests/consumer-idris.bats
