name: Build and Test a Single Version (Devcontainer)

on:
  workflow_call:
    inputs:
      idris-lsp-version:
        required: true
        type: string
      idris-version:
        required: true
        type: string

# Don't allow us to read from packages
permissions:
  contents: read

jobs:
  devcontainer-build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    env:
      BASE_TAG: localhost:5000/base-${{ inputs.idris-version }}:latest
      TAG: idris-devcontainer-${{ inputs.idris-lsp-version }}:test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup Buildx (no ARM)
        uses: docker/setup-buildx-action@v3
        with:
          # since we're using a local registry
          driver-opts: network=host
      
      - name: Build Base Image
        uses: ./.github/actions/build-base-img
        with:
          idris-version: ${{ inputs.idris-version }}
          push: true
          tags:  ${{ env.BASE_TAG }}

      - name: Run `docker image ls`
        run: docker image ls
      
      - name: Build Devcontainer Image
        uses: ./.github/actions/build-devcontainer-img
        with:
          idris-lsp-version: ${{ inputs.idris-lsp-version }}
          idris-version: ${{ inputs.idris-version }}
          load: true
          tags:  ${{ env.TAG }}
          base-tag: ${{ env.BASE_TAG }}
      
      - name: Setup Bats and Bats libs
        uses: bats-core/bats-action@3.0.1
        with:
          bats-version: 1.10.0
          support-version: 0.3.0
          support-path: ${{ github.workspace }}/.bats/bats-support
          assert-version: 2.1.0
          assert-path: ${{ github.workspace }}/.bats/bats-assert
          file-install: false
          detik-install: false

      # LIB_PATH is a env var I use in the setup() function of my bats tests
      # it points to the folder containing bats-assert and bats-support
      - name: Run Test
        env:
          LIB_PATH: ${{ github.workspace }}/.bats
          DOCKER_IMAGE: ${{ env.TAG }}
          IDRIS_VERSION: ${{ inputs.idris-version }}
        run: bats tests/devcontainer-idris.bats
