name: Deploy a single version (Devcontainer)

on:
  workflow_call:
    inputs:
      idris-lsp-version:
        required: true
        type: string
      idris-version:
        required: true
        type: string

permissions:
  packages: write
  contents: read

jobs:
  deploy-devcontainer:
    name: Deploy Devcontainer - ${{ inputs.idris-lsp-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@v2
        with:
          host: ${{ secrets.SSH_IP }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          private-key-name: oracle-arm
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          append: |
            - endpoint: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}

      - name: Login to GHCR
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha

      - name: Docker meta
        id: create-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}/base

      - name: Build Devcontainer
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: devcontainer.Dockerfile
          # we run this after base so we can pull the base_img from the registry
          build-args: | 
            IDRIS_LSP_VERSION=${{ inputs.idris-lsp-version }}
            IDRIS_LSP_SHA=${{ steps.get-sha.outputs.lsp-sha }}
            IDRIS_VERSION=${{ inputs.idris-version }}
            IDRIS_SHA=${{ steps.get-sha.outputs.idris-sha }}
            BASE_IMG=ghcr.io/joshuanianji/idris-2-docker/base:${{ inputs.idris-version }}
          tags: ghcr.io/${{ github.repository }}/base:${{ inputs.idris-lsp-version }}
          labels: ${{ steps.create-meta.outputs.labels }}
          push: true
          cache-from: type=gha,scope=build-devcontainer-${{ inputs.idris-lsp-version }}
