name: Build and Test a Single Version (Devcontainer)

on:
  workflow_call:
    inputs:
      idris-lsp-version:
        required: true
        type: string

# Don't allow us to read from packages
permissions:
  contents: read

jobs:
  devcontainer-build-test:
    name: Build Devcontainer
    runs-on: ubuntu-latest
    env:
      TAG: idris-devcontainer-${{ inputs.idris-lsp-version }}:test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Buildx (no ARM)
        uses: docker/setup-buildx-action@v2
        
      - name: Get Latest Idris Commit SHA
        id: get-sha
        uses: ./.github/actions/get-idris-sha

      - name: Build Devcontainer
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: devcontainer.Dockerfile
          build-args: | 
            IDRIS_LSP_VERSION=${{ inputs.idris-lsp-version }}
            IDRIS_LSP_SHA=${{ steps.get-sha.outputs.lsp-sha }}
          load: true
          tags: ${{ env.TAG }}
          cache-from: type=gha,scope=build-devcontainer-${{ inputs.idris-lsp-version }}

      - name: Setup Bats and Bats libs
        uses: brokenpip3/setup-bats-libs@1.5.2
        with:
          bats-version: '1.8.2'
          support-version: 0.3.0
          assert-version: 2.1.0
          file-install: false
          detik-install: false

      # LIB_PATH is a env var I use in the setup() function of my bats tests
      # it points to the folder containing bats-assert and bats-support
      - name: Run Test
        run: |
          export LIB_PATH=/usr/lib/
          export DOCKER_IMAGE=${{ env.TAG }}
          bats tests/devcontainer-idris.bats