name: "Build Image"
description: "Builds a Docker Image"

inputs:
  ssh_private_key:
    description: "The private key to use to connect to the builder"
    required: true
  ssh_user:
    description: "The user to use to connect to the builder"
    required: true
  ssh_ip:
    description: "The IP to use to connect to the builder"
    required: true
  github_token:
    description: "The github token to log into GHCR.io"
    required: true
  version:
    description: "The version of Idris to build"
    required: true
    type: string
  dockerfile:
    description: "Either 'base', 'debian', 'ubuntu' or 'devcontainer"
    required: true
    type: string

env:
  TAG: ghcr.io/${{ github.repository }}/${{ inputs.dockerfile }}:${{ inputs.version }}

runs:
  using: composite
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Buildx
      uses: "./.github/actions/setup-buildx"
      with:
        ssh_private_key: ${{ inputs.ssh_private_key }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_ip: ${{ inputs.ssh_ip }}

    - name: Get Latest Idris Commit SHA
      id: get-sha
      uses: ./.github/actions/get-idris-sha

    - name: Login to GHCR
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Docker meta
      id: create-meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ inputs.image-name }}

    - name: Build and push
      uses: docker/build-push-action@c56af957549030174b10d6867f20e78cfd7debc5
      with:
        context: .
        platforms: linux/arm64,linux/amd64
        push: true
        file: base.Dockerfile
        build-args: |
          IDRIS_VERSION=${{ inputs.version }}
          IDRIS_SHA=${{ steps.get-sha.outputs.sha }}
        tags: ${{ env.TAG }}

        # When doing matrix builds, we need to scope the image
        # https://github.com/moby/buildkit/issues/2885
        cache-from: type=gha,scope=build-test-${{ inputs.dockerfile }}-${{ inputs.version }}
        cache-to: type=gha,mode=max,scope=build-test-${{ inputs.dockerfile }}-${{ inputs.version }}